# GoReleaser 설정
# 사용법: goreleaser release --clean

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: docker-health-agent
    main: ./cmd/agent
    binary: docker-health-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"

# GitHub Actions에서 사용할 경우:
# env:
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
